Split layout into components
htmlacademy-vue/13051-pizza-1 pull request #2
Opened 2022-11-15 19:05 UTC by Isidora25

2022-11-16 06:41 UTC, xversus requested changes
Привет!

Есть некоторые проблемы в работе приложения:
1. Не отображаются картинки в хедере и шрифты по всему приложению:
![изображение](https://user-images.githubusercontent.com/25177385/202035505-5458f875-084b-4d08-ab37-d9c3596e5fe1.png)
2. Кнопка "Готовьте" должна быть неактивной, если не введено название пиццы или нет ни одного ингредиента (пункт ТЗ 3.2.7).
3. При нажатии на кнопку "Готовьте" нужно добавлять заказ в корзину (пункт ТЗ 3.2.7).
4. Если изначально не выбирать тесто и соус и добавить ингредиенты, они будут появляться на пустом месте без пиццы. Думаю, нужно либо проставить значения, чтобы пицца отображалась по умолчанию, либо заблокировать ингредиенты до выбора теста и соуса.

Более мелкие замечания оставил в комментах в PR.

2022-11-16 06:41 UTC, xversus commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +<style lang="scss" scoped>
Для лучшей читаемости блоки скриптов/стилей/разметки лучше разделять между собой пустой строкой. Это касается и других компонентов: ItemCounter, RadioButton, SelectorItem, AppLayout, все компоненты из builder/components.

2022-11-16 06:41 UTC, xversus commented on src/frontend/src/common/components/AppDrag.vue
> +    :draggable="true"
Пропсы с булевым типом и значением `true` можно пробрасывать проще:
`<div draggable>`

2022-11-16 06:41 UTC, xversus commented on src/frontend/src/main.js
> +// import App from "./App.vue";
В рабочем проекте лучше не оставлять закомментированный код, это затрудняет читаемость и создает проблемы при поддержке.

2022-11-16 06:41 UTC, xversus commented on src/frontend/src/views/Index.vue
> +      this.ingredients.map((item) => {
`map` применяется, когда нужно преобразовать элементы, получить таким образом новый массив и где-то его использовать. В твоем случае требуется просто пройтись по массиву и что-то сделать с его элементами, для этого используют `forEach`.  
Легко запомнить: в `map` передается чистая функция, в `forEach` - необязательно.  

Кроме того все, что выполняется в блоке if, лучше вынести в блок фигурными скобками. Так будет лучше читаться, даже если там одна строка.

2022-11-16 06:41 UTC, xversus commented on src/frontend/src/views/Index.vue
> +      set() {
Насколько вижу, значение `pizzaPrice` нигде не меняется, так что `set` здесь не нужен. Кроме того, в `set` не нужно ничего возвращать, наоборот, нужно обновлять значение переменной, которая используется в `get`.

2022-11-16 06:41 UTC, xversus commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                @setCount="(count) => setIngredient(count, ingredient)"
Здесь легко обойтись без стрелочной функции с помощью `$event`.

2022-11-16 06:41 UTC, xversus commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      require: true,
Опечатка: не `require`, а `required`. То же - в компоненте BuilderIngredientsSelector.vue.

2022-11-16 06:41 UTC, xversus commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      ingredient.count = count;
Изменять напрямую пропсы нельзя.

2022-11-21 15:49 UTC, xversus requested changes
Почти все исправлено, но кое-что осталось.
 
1. Сейчас пользователю сложно понять, какие тесто и соус выбраны по умолчанию, когда только загрузилась страница. Нужно выделять эти настройки в блоках "Выберите тесто" и "Выберите ингредиенты" соответственно.
2. По-прежнему не подтягивается нужный шрифт, не отображается иконка рядом со ссылкой "Войти", в отдельных местах `font-size` не бьется с образцом. Скорее всего, у тебя импортируются не все стили. Можешь запустить проект в папке template - там видно, как должно выглядеть приложение.

2022-11-21 16:44 UTC, Isidora25 commented
Спасибо за ревью, будет исправлено!
По поводу радио кнопок с выбором по умолчанию. Это лучше через свойство checked или с помощью v-model?

2022-11-21 18:09 UTC, xversus commented
> Спасибо за ревью, будет исправлено! По поводу радио кнопок с выбором по умолчанию. Это лучше через свойство checked или с помощью v-model?

С точки зрения того, чтобы меньше доработок внести, проще будет добавить пропсом `checked`. Если интересно, можешь попробовать повозиться с [поддержкой v-model](https://ru.vuejs.org/v2/api/index.html#model), но здесь, я думаю, это только усложнит код без очевидного профита.

2022-11-21 19:45 UTC, xversus approved these changes
Все хорошо, отличная работа! :)

2022-11-23 06:54 UTC, merged